[toolchain]


[features]
seeds = false
skip-lint = false

[programs.devnet]
api_integration = "ByB8NvWuXWG5KCw5MPY2kV478UY9VnVzhyss9bXPGYkb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "../keys/main.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
