[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
peer_token = "5wzfDw7tg2z1UKsAmqBMVm43tXTQxd8wVZYBYLHHhotW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/macbookpro/Solana/keys/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
