[toolchain]
rust = "1.85.1"
solana = "1.18.25"

[features]
seeds = false
skip-lint = false

[programs.devnet]
peer_token = "AyU7HfAP36feEsNTfAifzLxDcT7kCYPER6HxWeb7czmX"

[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "https://api.devnet.solana.com/"
wallet = "~/BlockChain/peer_rust_backend/peer-token/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
