[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
peer_token = "AafYBboNkNW5UKurnvBKLqkiuoD8sEcEZrZnRCuWScEV"

[registry]
url = "https://api.apr.dev"


[test]
upgradeable = true

[provider]
cluster = "Devnet"
wallet = "keys/Wallets/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
