[toolchain]
rust = "1.85.1"
solana = "1.18.25"

[features]
seeds = false
skip-lint = false



peer_token = "2UwS529cAMPeXwqEuF9P2HvZ1Y5ggTt4616PpC7uW1Tj"


[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "keys/Wallets/Company.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
