[toolchain]
rust = "1.85.1"
solana = "1.18.25"

[features]
seeds = false
skip-lint = false



peer_token = "9HmTP6ct3xSwHYPg3CwLftYw1trf75UVNx63gE95Qk8R"


[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "keys/Wallets/admin.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
