[toolchain]
rust = "1.85.1"
solana = "1.18.25"

[features]
seeds = false
skip-lint = false



<<<<<<< HEAD
peer_token = "HXoJTgD7WxQ9P4Y1dyg99agXHoMnr9S9iJ216Rky1hAY"
=======
peer_token = "6DzkgjSCmyaQxaWRgtigzCP4D3MFAVqvDYoij12fBoqC"

>>>>>>> development


[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "https://api.devnet.solana.com"
<<<<<<< HEAD
wallet = "/Users/macbookpro/Solana/keys/wallet.json"
=======
wallet = "keys/Wallets/Company.json"
>>>>>>> development


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
