[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
peer_token = "7tUBeYarZfa7mkhZeNoEanWyuUaZhStmbk89rXKj4ck9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
