[toolchain]
rust = "1.85.1"
solana = "1.18.25"

[features]
seeds = false
skip-lint = false



peer_token = "CYsrrJCrUUpW5Xc3jtjWcD8kUCvDT98aZ1TqkwsswMBd"


[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/macbookpro/Solana/keys/wallet.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
